# This is a short notebook to explore the features of the Task2 data-set
Tasks
- Data
- Cleaning / visualization

In [4]:
import pandas
import os
import sys
import pandas
import numpy
import logging

sys.path.append('..')
import data as dt

In [22]:
"""
Reading data
"""
x_test  = pandas.read_csv(os.path.join(dt.data_dir(), 'task2', 'X_test.csv'), header=0, index_col=0)
x_train = pandas.read_csv(os.path.join(dt.data_dir(), 'task2', 'X_train.csv'), header=0, index_col=0)
y_train = pandas.read_csv(os.path.join(dt.data_dir(), 'task2', 'y_train.csv'), header=0, index_col=0)

"""
Summary of data
"""
x_train.shape
x_train.describe()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x990,x991,x992,x993,x994,x995,x996,x997,x998,x999
count,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,...,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000
mean,-1.263735,-0.340837,0.582921,-0.274347,0.068664,-0.191351,-1.203202,-0.395419,0.415243,0.238060,...,-0.619778,-0.886824,-0.192149,0.655224,-0.944835,0.178099,0.203417,0.369598,-0.588700,-0.248469
std,1.209889,0.674918,0.702373,0.811545,0.888101,0.928947,1.135253,0.720173,0.642605,0.561557,...,1.039469,1.166296,0.719417,0.660375,0.989454,0.625333,0.687205,0.645052,0.638106,0.852974
min,-5.665421,-3.887293,-2.194176,-3.782391,-2.958118,-3.509899,-5.920954,-3.872502,-2.376961,-2.217859,...,-4.454111,-5.240292,-3.637851,-1.218816,-5.183132,-2.647403,-2.221092,-2.158761,-3.333840,-4.077775
25%,-2.223223,-0.732021,0.076249,-0.795827,-0.604431,-0.833292,-1.957883,-0.859385,0.001706,-0.110669,...,-1.398876,-1.778768,-0.640787,0.213543,-1.596008,-0.246600,-0.249065,-0.061726,-0.963063,-0.835805
50%,-0.983462,-0.236851,0.485271,-0.221096,-0.061674,-0.044504,-0.963773,-0.276232,0.341513,0.217322,...,-0.397732,-0.550050,-0.067554,0.551761,-0.779643,0.107084,0.158748,0.279761,-0.515746,-0.081172
75%,-0.271394,0.123312,1.033777,0.307701,0.737608,0.518062,-0.319050,0.136046,0.766660,0.557737,...,0.216220,0.040829,0.310919,0.996299,-0.158712,0.532684,0.582658,0.730698,-0.149383,0.392079
max,1.505870,1.570301,3.542413,2.135258,3.461174,3.115866,1.322524,1.523476,3.960671,2.578869,...,1.991493,1.567308,1.797739,3.952572,1.716352,2.895305,3.435469,3.217566,1.629311,1.992435

In [23]:
"""
Looking at the classes
"""
y_train

        y
id
0     1.0
1     0.0
2     1.0
3     1.0
4     1.0
5     1.0
6     2.0
7     1.0
8     1.0
9     1.0
10    0.0
11    1.0
12    0.0
13    1.0
14    1.0
15    0.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    2.0
22    1.0
23    0.0
24    0.0
25    0.0
26    1.0
27    1.0
28    1.0
29    1.0
...   ...
4770  1.0
4771  1.0
4772  1.0
4773  0.0
4774  1.0
4775  1.0
4776  1.0
4777  2.0
4778  1.0
4779  1.0
4780  1.0
4781  0.0
4782  2.0
4783  0.0
4784  1.0
4785  1.0
4786  1.0
4787  1.0
4788  1.0
4789  1.0
4790  2.0
4791  0.0
4792  1.0
4793  1.0
4794  0.0
4795  1.0
4796  1.0
4797  1.0
4798  0.0
4799  0.0

[4800 rows x 1 columns]